version: "3.9"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=fanto237(!)"
    ports:
      - "1433:1433"